# Generated by Django 5.1.3 on 2024-12-02 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('closed', 'Zamknięta')], default='active', max_length=255)),
                ('delivery_time', models.DateTimeField(null=True)),
                ('session_end_time', models.DateTimeField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_sessions', to='lunch_room.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LunchSessionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Uczestnik'), ('manager', 'Manager')], default='member', max_length=20)),
                ('lunch_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_room.lunchsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lunch_session')},
            },
        ),
        migrations.AddField(
            model_name='lunchsession',
            name='participants',
            field=models.ManyToManyField(related_name='participated_lunch_sessions', through='lunch_room.LunchSessionMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nazwa')),
                ('users', models.ManyToManyField(blank=True, related_name='order_groups', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
    ]
