# Generated by Django 5.1.3 on 2024-12-02 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_room', '0002_lunchsession_lunchsessionmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchsession',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_lunch_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
