# Generated by Django 5.1.3 on 2024-12-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_room', '0003_lunchsession_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSessionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('lunch_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_orders', to='lunch_room.lunchsession')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lunch_room.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lunch_session', 'user', 'meal')},
            },
        ),
    ]
