# Generated by Django 5.1.3 on 2024-12-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_room', '0004_lunchsessionorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchsessionorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
