services:
  # Celery Worker Service
  - type: worker
    name: celery-worker
    region: ohio
    runtime: python
    buildCommand: |
      cd lunch_room
      pip install -r requirements.txt
    startCommand: |
      cd lunch_room
      celery -A config worker --loglevel info --concurrency 4
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true

  # Django Web Service
  - type: web
    name: app
    region: ohio
    runtime: python
    buildCommand: |
      cd lunch_room
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py initializer
    startCommand: |
      cd lunch_room
      gunicorn config.wsgi:application
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false

  # Flower Service
  - type: web
    name: flower
    region: ohio
    plan: free
    runtime: python
    buildCommand: |
      cd lunch_room
      pip install -r requirements.txt
    startCommand: |
      cd lunch_room
      celery flower -A config --loglevel info --port $PORT
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true

  # Redis Service
  - type: redis
    name: celery-redis
    region: ohio
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []